# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ace's Home
email: f.a.lucifer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ace's property ... founded on 2016-3-23
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zgli1980.github.com" # the base hostname & protocol for your site
twitter_username: zgli1980
github_username:  zgli1980

# Build settings
markdown: kramdown
